//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AtomLabCoursesV1._0
{
    using System;
    using System.Collections.Generic;
    
    public partial class Course
    {
        public Course()
        {
            this.ActualRatings = new HashSet<ActualRating>();
            this.CoursesPriorities = new HashSet<CoursesPriority>();
            this.Rates = new HashSet<Rate>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string Teacher { get; set; }
        public Nullable<int> Field { get; set; }
        public Nullable<int> CourseLevel { get; set; }
        public Nullable<int> HoursNumber { get; set; }
        public string Details { get; set; }
        public string Image { get; set; }
        public Nullable<int> Rate { get; set; }
        public Nullable<int> Priority { get; set; }
    
        public virtual ICollection<ActualRating> ActualRatings { get; set; }
        public virtual Category Category { get; set; }
        public virtual ICollection<CoursesPriority> CoursesPriorities { get; set; }
        public virtual ICollection<Rate> Rates { get; set; }
    }
}
